# Generated by Django 5.1.2 on 2024-10-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_articles2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles2',
        ),
    ]
