# Generated by Django 5.1.2 on 2024-10-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_articles_published_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='article_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='articles',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
